import {Action} from "../../types.ts";
import {asRelativeImport} from "../asRelativeImport.ts";

/**
 * Create a file that imports all actions.
 */
export const generateActionRegistryTs = (actions: Action[], serverOutDir: string, registryPath: string): string => {
  const actionsWithRelativePaths = actions.map(action => {
    return {
      ...action,
      relativeSourceFilePath: asRelativeImport(action.sourceFilePath, serverOutDir),
    };
  })

  let newCode = `// Generated by RSF Zero, do not modify
`;
  for (const action of actionsWithRelativePaths) {
    if (action.name === 'default') {
      newCode += `import ${action.id} from '${action.relativeSourceFilePath}';
`;
    } else {
      newCode += `import { ${action.name} as ${action.id} } from '${action.relativeSourceFilePath}';
`;
    }
  }
  return newCode;
}

export const generateEmptyActionRegistry = (): string => {
  return `// Generated by RSF Zero, do not modify
export const actionRegistry = {};
`;
}
