import {Action} from "../../types.ts";
import {asRelativeImport} from "../asRelativeImport.ts";
import {replaceFileExt} from "../replaceFileExt.ts";


/**
 * Create a typescript file that imports all actions. This can then be passed to a tsc to be processed into dist js files.
 */
export const generateActionRegistryTs = (actions: Action[], registryPath: string): string => {
  const actionsWithRelativePaths = actions.map(action => {
    return {
      ...action,
      relativeSourceFilePath: asRelativeImport(action.sourceFilePath, registryPath),
    };
  })

  let newCode = `// Generated by RSF Zero, do not modify
`;
  for (const action of actionsWithRelativePaths) {
    if (action.name === 'default') {
      newCode += `import ${action.id} from '${action.relativeSourceFilePath}';
`;
    } else {
      newCode += `import { ${action.name} as ${action.id} } from '${action.relativeSourceFilePath}';
`;
    }
  }
  return newCode;
}

/**
 * Create a javascript file that imports all actions. This is used by the start command to load action functions when the server starts.
 */
export const generateActionRegistryJs = (actions: Action[], relativeToDir: string): string => {
  const actionsWithRelativePaths = actions.map(action => {
    return {
      ...action,
      relativeSourceFilePathAsJs: replaceFileExt(asRelativeImport(action.sourceFilePath, relativeToDir), '.js'),
    };
  })

  let newCode = `// Generated by RSF Zero, do not modify
`;

  for (const action of actionsWithRelativePaths) {
    if (action.name === 'default') {
      newCode += `import ${action.id} from '${action.relativeSourceFilePathAsJs}';
`;
    } else {
      newCode += `import { ${action.name} as ${action.id} } from '${action.relativeSourceFilePathAsJs}';
`;
    }
  }

  newCode += `
export const actionRegistry = {
${actionsWithRelativePaths.map(action => `"${action.id}": ${action.id},`).join('\n')}
};
`;
  return newCode;
}

export const generateEmptyActionRegistryJs = (): string => {
  return `// Generated by RSF Zero, do not modify
export const actionRegistry = {};
`;
}
